version: "2"

services:
  redis:
    image: redis
    container_name: gamenews_redis
    volumes:
      - redis_data:/data
    command: --appendonly yes --requirepass "123456"
    restart: always

  db:
    image: postgres:11.5-alpine
    container_name: gamenews_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
    restart: always
    ports:
      - "5432:5432"

  # RabbitMQ - queue
  rabbit:
    container_name: gamenews_rabbit
    image: rabbitmq:3.8.0-management-alpine
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin

  web:
    build: .
    container_name: gamenews_web
    command: gunicorn display.wsgi:application --bind 0.0.0.0:8000 -w4
    volumes:
      - .:/usr/src/app/
    env_file: .env
    depends_on:
      - db
      - redis
    restart: always

  nginx:
    build: ./nginx
    container_name: gamenews_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
    restart: always

volumes:
  postgres_data:
  redis_data:
