version: "2"

services:
  redis:
    image: redis
    container_name: gamenews_redis
    volumes:
      - redis_data:/data
    command: --appendonly yes --requirepass "123456"
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:11.5-alpine
    container_name: gamenews_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: pro.env
    restart: always
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: gamenews_web
    command: gunicorn display.wsgi:application --bind 0.0.0.0:8000 -w4
    volumes:
      - .:/usr/src/app/
    env_file: pro.env
    depends_on:
      - db
      - redis
    restart: always
    ports:
      - "8000:8000"

  frpc:
    image: snowdreamtech/frpc
    container_name: gamenews_frpc
    volumes:
      - "./frpc/frpc.ini:/etc/frp/frpc.ini"
    restart: always

volumes:
  postgres_data:
  redis_data:
  static:
  media:

networks:
  default:
    external:
      name: gamenews_network